# Auth
CREATE TABLE User
(
    ID          INTEGER            NOT NULL PRIMARY KEY AUTO_INCREMENT,
    Name        VARCHAR(50)        NOT NULL UNIQUE,
    Email       VARCHAR(255)                DEFAULT NULL UNIQUE,
    Password    VARCHAR(255)       NOT NULL,
    CreatedAt   TIMESTAMP          NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    AvatarUrl   VARCHAR(255)                DEFAULT NULL,
    Description TEXT                        DEFAULT NULL,
    Color       MEDIUMINT UNSIGNED NOT NULL DEFAULT 16777215,
    System      BOOLEAN            NOT NULL,
    FriendCode  BINARY(16)         NOT NULL DEFAULT UNHEX(SYS_GUID()) UNIQUE
);

CREATE TABLE Session
(
    ID        INTEGER      NOT NULL PRIMARY KEY AUTO_INCREMENT,
    UserId    INTEGER      NOT NULL,
    Token     VARCHAR(255) NOT NULL UNIQUE,
    Name      VARCHAR(255) NOT NULL,
    CreatedAt TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    ExpiresAt TIMESTAMP    NOT NULL DEFAULT DATE_ADD(CURRENT_TIMESTAMP(), INTERVAL 7 DAY),
    FOREIGN KEY (UserId) REFERENCES User (ID) ON DELETE CASCADE
);

# Members
CREATE TABLE Member
(
    ID          BIGINT             NOT NULL,
    UserId      INTEGER            NOT NULL,
    Name        VARCHAR(255)       NOT NULL,
    Pronouns    VARCHAR(255)                DEFAULT NULL,
    AvatarUrl   VARCHAR(255)                DEFAULT NULL,
    Description TEXT                        DEFAULT NULL,
    Color       MEDIUMINT UNSIGNED NOT NULL DEFAULT 16777215,
    CreatedAt   TIMESTAMP          NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UpdatedAt   TIMESTAMP          NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
    Archived    BOOLEAN            NOT NULL DEFAULT FALSE,
    Custom      BOOLEAN            NOT NULL DEFAULT FALSE,
    PRIMARY KEY (ID, UserId),
    FOREIGN KEY (UserId) REFERENCES User (ID) ON DELETE CASCADE
);

# Friends
CREATE TABLE Friend
(
    Friend1 INTEGER NOT NULL,
    Friend2 INTEGER NOT NULL,
    PRIMARY KEY (Friend1, Friend2),
    FOREIGN KEY (Friend1) REFERENCES User (ID) ON DELETE CASCADE,
    FOREIGN KEY (Friend2) REFERENCES User (ID) ON DELETE CASCADE
);

CREATE TABLE FriendRequest
(
    FromUser INTEGER NOT NULL,
    ToUser   INTEGER NOT NULL,
    PRIMARY KEY (FromUser, ToUser),
    FOREIGN KEY (FromUser) REFERENCES User (ID) ON DELETE CASCADE,
    FOREIGN KEY (ToUser) REFERENCES User (ID) ON DELETE CASCADE
);

CREATE TABLE FriendSettings
(
    UserId          INTEGER NOT NULL,
    FriendId        INTEGER NOT NULL,
    PermissionLevel TINYINT NOT NULL DEFAULT FALSE,
    NotifyMe        BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (UserId, FriendId),
    FOREIGN KEY (UserId) REFERENCES User (ID) ON DELETE CASCADE,
    FOREIGN KEY (FriendId) REFERENCES User (ID) ON DELETE CASCADE
);

# Folders
CREATE TABLE Folder
(
    ID          BIGINT             NOT NULL,
    UserId      INTEGER            NOT NULL,
    ParentId    BIGINT                      DEFAULT NULL,
    Name        VARCHAR(255)       NOT NULL,
    Description TEXT                        DEFAULT NULL,
    Emoji       VARCHAR(3)                  DEFAULT NULL,
    Color       MEDIUMINT UNSIGNED NOT NULL DEFAULT 16777215,
    CreatedAt   TIMESTAMP          NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UpdatedAt   TIMESTAMP          NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
    PRIMARY KEY (ID, UserId),
    FOREIGN KEY (UserId) REFERENCES User (ID) ON DELETE CASCADE,
    FOREIGN KEY (ParentId, UserId) REFERENCES Folder (ID, UserId) ON DELETE CASCADE
);

CREATE TABLE MemberFolder
(
    UserId   INTEGER NOT NULL,
    MemberId BIGINT  NOT NULL,
    FolderId BIGINT  NOT NULL,
    PRIMARY KEY (UserId, MemberId, FolderId),
    FOREIGN KEY (UserId) REFERENCES User (ID) ON DELETE CASCADE,
    FOREIGN KEY (FolderId, UserId) REFERENCES Folder (ID, UserId) ON DELETE CASCADE,
    FOREIGN KEY (MemberId, UserId) REFERENCES Member (ID, UserId) ON DELETE CASCADE
);

# Front
CREATE TABLE Front
(
    ID        BIGINT    NOT NULL,
    UserId    INTEGER   NOT NULL,
    MemberId  BIGINT    NOT NULL,
    StartedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    EndedAt   TIMESTAMP          DEFAULT NULL,
    Comment   VARCHAR(255)       DEFAULT NULL,
    UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
    PRIMARY KEY (ID, UserId),
    FOREIGN KEY (UserId) REFERENCES User (ID) ON DELETE CASCADE,
    FOREIGN KEY (MemberId, UserId) REFERENCES Member (ID, UserId) ON DELETE CASCADE
);

# Custom Fields
CREATE TABLE CustomField
(
    ID       BIGINT       NOT NULL,
    UserId   INTEGER      NOT NULL,
    Name     VARCHAR(255) NOT NULL,
    DataType VARCHAR(8)   NOT NULL,
    PRIMARY KEY (ID, UserId),
    FOREIGN KEY (UserId) REFERENCES User (ID) ON DELETE CASCADE
);

CREATE TABLE CustomFieldData
(
    ID        BIGINT  NOT NULL,
    UserId    INTEGER NOT NULL,
    MemberId  BIGINT  NOT NULL,
    DataValue TEXT DEFAULT NULL,
    PRIMARY KEY (ID, UserId),
    FOREIGN KEY (UserId) REFERENCES User (ID) ON DELETE CASCADE,
    FOREIGN KEY (MemberId, UserId) REFERENCES Member (ID, UserId) ON DELETE CASCADE
);