CREATE TABLE Front
(
    ID        BIGINT    NOT NULL PRIMARY KEY AUTO_INCREMENT,
    UserId    INTEGER   NOT NULL,
    MemberId  BIGINT    NOT NULL,
    StartedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    EndedAt   TIMESTAMP          DEFAULT NULL,
    Comment   VARCHAR(255)       DEFAULT NULL,
    UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
    FOREIGN KEY (UserId) REFERENCES User (ID) ON DELETE CASCADE,
    FOREIGN KEY (MemberId) REFERENCES Member (ID) ON DELETE CASCADE
);