CREATE TABLE FriendRequest
(
    FromUser INTEGER NOT NULL,
    ToUser   INTEGER NOT NULL,
    PRIMARY KEY (FromUser, ToUser),
    FOREIGN KEY (FromUser) REFERENCES User (ID) ON DELETE CASCADE,
    FOREIGN KEY (ToUser) REFERENCES User (ID) ON DELETE CASCADE
);

CREATE TABLE Friend
(
    UserId          INTEGER NOT NULL,
    FriendId        INTEGER NOT NULL,
    PermissionLevel TINYINT NOT NULL DEFAULT FALSE,
    NotifyMe        BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (UserId, FriendId),
    FOREIGN KEY (UserId) REFERENCES User (ID) ON DELETE CASCADE,
    FOREIGN KEY (FriendId) REFERENCES User (ID) ON DELETE CASCADE
);