ALTER TABLE Member
    ADD COLUMN Sort
        MEDIUMINT UNSIGNED NOT NULL
        DEFAULT 0
        AFTER UserId;

ALTER TABLE Folder
    ADD COLUMN Sort
        MEDIUMINT UNSIGNED NOT NULL
        DEFAULT 0
        AFTER UserId;